# fly.toml app configuration file generated for chaloeil-bot on 2023-11-26T04:33:30+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chaloeil-bot"
primary_region = "ams"

[build]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 512
